workflows:
  build_apk:
    name: Build APK
    max_build_duration: 30
    environment:
      flutter: stable
    working_directory: Mofakeratalmohany
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - Mofakeratalmohany/build/app/outputs/flutter-apk/app-release.apk
