workflows:
  build_apk:
    name: Build Android APK
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
    working_directory: mofakera_app
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
