workflows:
  build_apk:
    name: Build Android APK
    instance_type: linux # استخدام بيئة Linux المجانية
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
