workflows:
  build_apk:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
      vars:
        PROJECT_DIR: "mofakera_app"
    scripts:
      - name: Install dependencies
        script: |
          cd $PROJECT_DIR
          flutter pub get
      - name: Build APK
        script: |
          cd $PROJECT_DIR
          flutter build apk --release
    artifacts:
      - mofakera_app/build/app/outputs/flutter-apk/app-release.apk
